### PR TITLE
fix: don't spread errors blindly

### PR DESCRIPTION
**Pull request by Gopikrishna19**
This is to fix recurring problems with @@iterator #207 #211

### The problem

```
{ AggregateError: 
    TypeError: Found non-callable @@iterator
        at verifyConditions (/node_modules/@semantic-release/npm/index.js:39:12)
        at /node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: 'AggregateError' }
```
```
{ AggregateError: 
    TypeError: Found non-callable @@iterator
        at verifyConditions (/node_modules/@semantic-release/npm/index.js:38:12)
        at /node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: 'AggregateError' }
```

The errors refer to the following lines where we are spreading the error. If there is another error that is not thrown by an underlying utility function that is not an array then, spreading that causes the `non-callable @@iterable` error.

https://github.com/semantic-release/npm/blob/b26b6e9f8f9ec384a6332e4e623ec6ce6ec9b15f/index.js#L38-L40

### The fix

Do not spread the error blindly, rather concatenate it to the errors list.

### CODE REVIEW

**Comment by gr2m** [comment]
Can you add some more context on what the problem is, and how your code fixes it? Can you add tests to avoid future regressions?

**Comment by Gopikrishna19** [comment]
@gr2m the two issues I linked about gives a detailed explanation of what the problem is. The tests existing tests should not break as the behaviour did not change, merely a refactor.

```js
errors.push(...error); // fails if error is not iterable

errors = errors.concat(error); // works for both array as well as non iterable entities

// example non-iterable
[1, 2, 3].concat(4) === [1, 2, 3, 4];  // true

// example iterable
[1, 2, 3].concat([4, 5]) === [1, 2, 3, 4, 5];  // true
```

Hope that helps. There is no behaviour change and there shouldn't be any tests breaking.

**Comment by Gopikrishna19** [comment]
Thinking again, I can add a test against throwing a non-iterable object. I am not exactly familiar with the testing style you guys have here. I would be happy to add the tests if you guys can help me a bit on where to put and how to mock. Generally, in `jest`, I'd do something like (pseudo):

```js
jest.mock(verifyNpmConfig).mockRejectedValues(nonIterableErrorThatHappenedForSomeOtherReason);

expect(() => verifyConditions()).toThrow([nonIterableErrorThatHappenedForSomeOtherReason]); 
                                         // to be aggregated without throwing @@iterable error
```

**Comment by gr2m** [comment]
okay I got it now, cheers. However it seems that the code change did in fact change some behavior, can you look into the failing tests?

**Comment by Gopikrishna19** [comment]
It's not passing in Windows or Windows WSL. Even master is not working. Is there a specific setup I have to do to replicate the testing environment? 

Theoretically speaking it shouldn't break at all 🤔 

I guess you guys are mutating the original error array by using push and the tests are based on that. If I can't replicate the environment I shall try reverting the command to push but use an array check before spreading. Pushing in a few mins.

**Comment by Gopikrishna19** [comment]
@gr2m please approve for tests now. I wasn't able to test locally as Windows as the testing environment is not working.

**Comment by Gopikrishna19** [comment]
I can't build it locally to test the PR and see why it is failing. Closing it. Hope someone else with a testable env takes this work. Or I can reopen the PR if/when authors support platform-independent development. Thank you for the opportunity!

**Pull request closed without merging**
