### PR TITLE
fix: setting tarballDir to CWD causes fs-extra error

### LINKED ISSUE #169: setting tarballDir to CWD causes fs-extra error
After upgrading to fs-extra v8.0.0, fs-extra will throw an error whenever the "source" and "destination" paths are equal.

Error:
```
[2:37:29 AM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
[2:37:29 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Source and destination must not be the same.
    at getStats (/home/travis/build/Colonise/[secure]/node_modules/fs-extra/lib/util/stat.js:82:17)
    at fs.stat (/home/travis/build/Colonise/[secure]/node_modules/fs-extra/lib/util/stat.js:40:16)
    at FSReqWrap.oncomplete (fs.js:154:5) pluginName: '@semantic-release/npm' }
{ Error: Source and destination must not be the same.
    at getStats (/home/travis/build/Colonise/[secure]/node_modules/fs-extra/lib/util/stat.js:82:17)
    at fs.stat (/home/travis/build/Colonise/[secure]/node_modules/fs-extra/lib/util/stat.js:40:16)
    at FSReqWrap.oncomplete (fs.js:154:5) pluginName: '@semantic-release/npm' }
```

Config:
```
{
    tarballDir: '.'
}
```

Error occurs at https://github.com/semantic-release/npm/blob/9a6176d973ae0a7b1f060e1d85a8035a7bf57ab5/lib/prepare.js#L35

Possible solution:
Check if tarballDir will actually change the output before calling move()
`path.resolve(cwd, tarballDir.trim()) === path.resolve(cwd)`

### PR DESCRIPTION
**Pull request by pathurs**
fixes #169

### CODE REVIEW

**Comment by gr2m** [comment]
Could you check the linting errors 🙏

**Comment by pathurs** [comment]
I've fixed the prettier lint error, however a quick glance at the tests looks like it'd take me more than a few moments to add coverage for my changes.

I can try and fix this later, but will need to find some time :)

**Comment by gr2m** [comment]
No worries, take your time. Thanks for your help!

**Comment by pathurs** [comment]
I couldn't get Docker to install on my version of Windows, so I am writing the test semi-blind.

**Comment by pathurs** [comment]
Looks like my tests worked

**Pull request merged**
