### PR TITLE
Support OTP fetching from config.otpUrl

### PR DESCRIPTION
**Pull request by dominykas**
[Tested](https://travis-ci.org/dominykas/allow-scripts/jobs/551973725) on one of [my own packages](https://github.com/dominykas/allow-scripts/compare/f3511752d7a4e185e14725b3e42572937852889c...c6a94eafd52fcc97536f67a51e07a61597b291d8#diff-d0fd6e011e62dec6517327248cb7766bR5): works like magic!

I think I got the coverage right, but I'm still not sure how to assert that `--otp` was passed through to npm. npm will send the [OTP inside the `npm-otp` header](https://github.com/npm/npm-registry-fetch/blob/5dbd1d722b9125026eea1f0ef019119598e7bfb0/index.js#L188), but short of adding a proxy around the couch app, I'm not sure if it's even possible to observe that in any way.

See also: #93

### CODE REVIEW

**Comment by pvdlg** [comment]
Maybe I'm missing something here but that seems to be a huge security hole...
Anyone can look at the URL you configure in `otpUrl` calls it, get your OTP and release anything with your account.

**Comment by dominykas** [comment]
No, they cannot release anything, because

a) I need to press a button on my phone (although I'll admit that someone could configure a server to respond without that, however that's no worse than no 2FA at all)
b) OTP is not enough - you still need the token (so once again - no worse than 2FA)

**Comment by dominykas** [comment]
Also the URL should be kept as secret as the token (i.e. in env). I can easily update this to only use `process.env.NPM_OTP_URL` if that's the preferred route?

**Comment by pvdlg** [comment]
Reading through the documentation of https://github.com/nearform/optic I don't think using it require any modification in this plugin.

In your CI you could simply set `NPM_CONFIG_OTP` (which is equivalent of passing the OPT via --otp).

Because the OTP is valid only for a few seconds you could do that via a `prepublishOnly` step in your `package.json` so it would be executed just before semantic-release runs `npm publish`:
```json
{
 "scripts": {
    "prepublishOnly": "export NPM_CONFIG_OTP=$(curl -s $NPM_OTP_URL/$OTP_TOKEN)"
  }
}
```

I would rather not make any change in this plugin not recommending any particular solution in the doc out of security concern.

**Comment by dominykas** [comment]
I was not aware you could set it this way - I'll try that out, thank you.

I will try this out and report back.

I have no intent of recommending any particular solution, but if this approach works - I suppose some documentation is in order - I'll see if I can find a place to PR that.

**Comment by dominykas** [comment]
No luck: https://travis-ci.org/dominykas/allow-scripts/jobs/575685664#L310

I suspected this might happen, because I had tried playing around with env vars in a different context - they don't carry through, i.e. npm does not see an env vars from one of `scripts` inside another one.

I'll try writing the otp into an `.npmrc` next, but IIRC, the config for `publish` is loaded _before_ `prepublishOnly` executes, so I'm not sure that will have an effect either.

**Comment by dominykas** [comment]
No luck: https://travis-ci.org/dominykas/allow-scripts/jobs/575690340#L316

It can probably be worked around by using the `exec` plugin, but it seems to me that this is a behavior that's important enough to be built-in, rather than worked around?

Would it make sense to replace `otpUrl` with an `otpCommand` to make it more flexible (with `curl -s $URL` being one way to configure the command)?

**Comment by pvdlg** [comment]
In your first test the error is `The local branch master is behind the remote one, therefore a new version won't be published.` so the failure is not related to the OTP token.

**Comment by dominykas** [comment]
> In your first test the error is The local branch master is behind the remote one, therefore a new version won't be published. so the failure is not related to the OTP token.

The link I have points to line 310 in the log... but the log does not contain such a line. The release job also ran 1.5 hours later than the test jobs, so I suspect for whatever reason (quite possibly by accident) I restarted the build.

I'll see if there's a way to recover the original logs, but I'm fairly certain it was an `EOTP` originally.

**Comment by pvdlg** [comment]
Closing per https://github.com/semantic-release/npm/pull/234#issuecomment-565683509

**Pull request closed without merging**
