### PR TITLE
publish to latest

### LINKED ISSUE #158: Version 5.1.5 and above has not been published to npm registry
When trying to update semantic-release to the latest version to resolve some vulnerabilities I found that @semantic-release/npm has not been publishing releases to npm. These are all introduced by the npm module which was updated in version 5.1.5, the first version not to be published.
```
───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ semantic-release                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ semantic-release > @semantic-release/npm > npm > libcipm >   │
│               │ npm-lifecycle > node-gyp > tar                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/803                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ semantic-release                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ semantic-release > @semantic-release/npm > npm > node-gyp >  │
│               │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/803                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ semantic-release                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ semantic-release > @semantic-release/npm > npm >             │
│               │ npm-lifecycle > node-gyp > tar                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/803              
```

### PR DESCRIPTION
**Pull request by gr2m**
closes #158. Ping @pvdlg any objections?

### CODE REVIEW

**Comment by pvdlg** [comment]
So far the process on each module is to publish on `@next` with semantic-release and manually use `npm dist-tag add` to make the version available on `@latest`.

All that will be automated when we move to version 16.

**Comment by gr2m** [comment]
Maybe it’s time to move to version 16, even if it’s not perfect?

**Comment by pvdlg** [comment]
Yes agreed. It's quite a process to do the migration. Everything merged in a certain order.
I should have a week of vacation in between projects in two weeks and I can do that then and catch up on the stack of issue across all the repo.

**Comment by gr2m** [comment]
Okay sounds good, happy to set up a remote coworking day to help out in any way I can

**Comment by pvdlg** [comment]
Closing as we'll handle that when we move all repo to v16. The change is already done on the `beta` branch and it will be merged during the migration.

**Pull request closed without merging**
